version: '3'

services:
  app:
    build:
      context: .
    ports: # host and image ports respectively
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000" # run django server on port 8000 on local machine
